* Adding coverage report * First try at incorporating SonarCloud orb commands

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -94,9 +94,58 @@ jobs:
       - run:
           name: Run tests
           # Use built-in Django test module
-          command: python manage.py test --keep
+          command: coverage run --source='.' manage.py test --keep || echo "test fails"
           working_directory: ~/project/django-backend/
 
+      - run:
+          name: setup coverage dir
+          command: mkdir ~/project/coverage-reports
+
+      - run:
+          name: Make XML coverage report
+          command: coverage xml -o ~/project/coverage-reports/coverage.xml
+          working_directory: ~/project/django-backend
+
+      - run:
+          name: ls testsing
+          command: ls -l  ~/ && ls -l ~/project && ls -l ~/project/coverage-reports
+
+      - run:
+          name: cat coverage
+          command: cat ~/project/coverage-reports/coverage.xml
+
+
+
+      # Sonar cloud setup and scanning
+      - run:
+          name: Create cache directory if it doesn't exist
+          command: mkdir -p /tmp/cache/scanner
+      - restore_cache:
+          keys:
+            - v<<parameters.cache_version>>-sonarcloud-scanner-4.6.2.2472
+      - run:
+          name: SonarCloud
+          command: |
+            set -e
+            VERSION=4.6.2.2472
+#            SONAR_TOKEN=$<<parameters.sonar_token_variable_name>>
+            SCANNER_DIRECTORY=/tmp/cache/scanner
+            export SONAR_USER_HOME=$SCANNER_DIRECTORY/.sonar
+            OS="linux"
+            echo $SONAR_USER_HOME
+            if [[ ! -x "$SCANNER_DIRECTORY/sonar-scanner-$VERSION-$OS/bin/sonar-scanner" ]]; then
+              curl -Ol https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$VERSION-$OS.zip
+              unzip -qq -o sonar-scanner-cli-$VERSION-$OS.zip -d $SCANNER_DIRECTORY
+            fi
+
+            chmod +x $SCANNER_DIRECTORY/sonar-scanner-$VERSION-$OS/bin/sonar-scanner
+            chmod +x $SCANNER_DIRECTORY/sonar-scanner-$VERSION-$OS/jre/bin/java
+            $SCANNER_DIRECTORY/sonar-scanner-$VERSION-$OS/bin/sonar-scanner
+          environment:
+            SONARQUBE_SCANNER_PARAMS: '{"sonar.host.url":"https://sonarcloud.io"}'
+      - save_cache:
+          key: v<<parameters.cache_version>>-sonarcloud-scanner-4.6.2.2472
+          paths: /tmp/cache/scanner
 
 # Invoke jobs via workflows
 # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
